sudo: required
services:
  - docker
before_install: 
  - docker build -t 05061995/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true 05061995/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-2" #aws region
  app: "nameOfAppEnvWhichYouCreatedInBeanStalk"
  bucket_name: "bucketName" #travis ci copy all the file in github and zip into one file and put it in S3 so the it can be accessed by beanstalk
  bucket_path: "nameOfAppEnvWhichYouCreatedInBeanStalk " # same as app name above 
  on:
   branch: master #only deploy when master branch has new code
  access:key_id: $envVaribleOfTravisHoldingAwsSecretKey
  secret_access_key: "$AWS_SECRET_KEY"
